### ISSUE TITLE
New gem release include ruby 2.2 and rubyzip compat fixes

### ISSUE THREAD

**Issue by xaviershay** [randym/axlsx#376]
The current gem release is broken for everyone using a modern environment, and as such we have to run off git master.

Please do consider releasing a new gem soon :)

Cheers,
Xavier

**Comment by joshuairl** [comment]
Maybe this is where the errors are coming from that I was experiencing with "split"?

**Comment by jurriaan** [comment]
Hi @xaviershay,
I've just released a pre-release version. (v2.1.0.pre)
Please test it and report if you have any problems

**Comment by g3d** [comment]
Got problem with opening file in MS Excel for Mac, Libreoffice opens file without problem.

File: https://www.dropbox.com/s/8kx4q9yvoysrlqt/students-invalid.xlsx?dl=0

![screen_shot_2015-03-26_at_6 51 29_pm](https://cloud.githubusercontent.com/assets/859210/6851731/78916326-d3e9-11e4-9ce0-4cccb356ac3f.png)

**Comment by nodo** [comment]
same problem as @g3d

**Comment by nodo** [comment]
looks like I was using the wrong version. Using:
```
gem 'axlsx', '~> 2.0'
````
Solved the issue.

**Comment by silviorelli** [comment]
Same problem for me, I tried with 2.0.1, 2.1.0.pre and directly with the repo at the last commit.
I'm on Rails 4.2.1 and Ruby 2.2.1.

I've seen from older closed issues that the same problem happened in the past and was due to the zip compression: the last gem installs rubyzip 1.1.7 but this does not solve the problem.

**Comment by tranngocsam** [comment]
I'm having problem using this gem with rubyzip 1.1.7, I don't want to downgrade rubyzip, because I want to use the latest version of roo gem

**Comment by xaviershay** [comment]
Apologies I missed the update here. We're no longer using this gem (were able to remove the feature).

**Comment by noniq** [comment]
There's now https://github.com/caxlsx/caxlsx where we have released 3.0.0, 3.0.1, and even 2.0.2 containing a backport for the rubyzip dependency problem.
